const express = require('express');
const { registrarUsuario, loginUsuario, getUsuarios, updateUsuario, deleteUsuario } = require('../controllers/userController');
const validateRegistro = require('../middleware/validateRegistro');
const validateUpdateUsuario = require('../middleware/validateUpdateUsuario');
const router = express.Router();
router.post('/registro', validateRegistro, registrarUsuario);
router.post('/login', loginUsuario);
router.get('/', getUsuarios);
router.put('/:id', validateUpdateUsuario, updateUsuario);
router.delete('/:id', deleteUsuario);
module.exports = router;